version: '3'
services:
  elastic:
    image: elasticsearch:7.17.8
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1000m -Xmx1000m
    ports:
      - 9200:9200
  redis:
    image: redis:7.0.7
    ports:
      - 6379:6379